"""Got rid of Playlist table

Revision ID: 64b4f3ad3f7f
Revises: f33fa5888b02
Create Date: 2017-12-17 20:03:30.590419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b4f3ad3f7f'
down_revision = 'f33fa5888b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlists')
    op.drop_table('on_playlist')
    op.add_column('songs', sa.Column('album_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'songs', 'albums', ['album_id'], ['id'])
    op.drop_constraint('users_friend_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'friend_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_friend_id_fkey', 'users', 'person', ['friend_id'], ['id'])
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'album_id')
    op.create_table('on_playlist',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playlist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='on_playlist_playlist_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['songs.id'], name='on_playlist_user_id_fkey')
    )
    op.create_table('playlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='playlists_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='playlists_pkey')
    )
    # ### end Alembic commands ###
