"""changed person table

Revision ID: 64e9a13887d3
Revises: 
Create Date: 2017-12-15 01:10:27.951073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e9a13887d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('person', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'person', 'users', ['email'], ['email'])
    op.drop_constraint('songs_title_key', 'songs', type_='unique')
    op.drop_column('songs', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('genre', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint('songs_title_key', 'songs', ['title'])
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'name')
    op.drop_column('person', 'email')
    # ### end Alembic commands ###
