"""associated friends with users

Revision ID: f33fa5888b02
Revises: e3b2d9eb7b61
Create Date: 2017-12-17 18:41:31.572473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33fa5888b02'
down_revision = 'e3b2d9eb7b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('person_name_key', 'person', type_='unique')
    op.create_foreign_key(None, 'person', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('friend_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'person', ['friend_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'friend_id')
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.create_unique_constraint('person_name_key', 'person', ['name'])
    op.drop_column('person', 'user_id')
    # ### end Alembic commands ###
